## Apply Savitzky-Golay Filter on DEA FC data

In [10]:
### Essential Libary Imports
import numpy as np
import pandas as pd
from datetime import datetime

import sys
import os 
from sklearn.pipeline import Pipeline

# Import Custom Module
sys.path.append('C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/ANCILLARY_SCRIPTS')
from Preprocess_Data import * # import from custom transformers

In [11]:
## Create a list of DEA FC files that are currently present in the directory 
files = os.listdir(f'../DATASETS/DEA_FC_PROCESSED/SPATIAL_AND_UE_FILTER/')
files = [i.split('.')[0] for i in files]
all_dea_fc = files[1:]

In [12]:
## Savitzky-Golay Filter Parameters:
window_length_smooth = 15
polyorder = 4

In [ ]:
## Main Loop where we are going through through the list of datafiles,
##  reading them in, applying the Savitzky-Golay Filter, and saving them to an output,
##  all in an iterative fashion
max_counter = len(all_dea_fc)
counter = 1
print(f'The Data Awaiting Preprocessing: {all_dea_fc}')

for site_location_name in all_dea_fc:
    print(f'Processing Data for {site_location_name}, {counter}/{max_counter}')
    
    # Read in the File 
    site = pd.read_csv(f'C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/DATASETS/DEA_FC_PROCESSED/SPATIAL_AND_UE_FILTER/{site_location_name}.csv', parse_dates=['time'])
    
    # The Savitzky-Golay Filter pipeline 
    time_fc_pipeline = Pipeline([
        ('preprocess_fc_time_series', 
        preprocess_fc_time_series(window_length = window_length_smooth, polyorder = polyorder))
    ])
    site_resampled = time_fc_pipeline.fit_transform(site)
    
    # Export the processed dataset 
    site_merged = site_resampled.copy()
    site_merged.to_csv(f'C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/DATASETS/DEA_FC_PROCESSED/MODELLED_PREPROCESSED/Input_DataSet_{site_location_name}.csv')
    
    print(f'Data for {site_location_name} Exported  {counter}/{max_counter}')

The Data Awaiting Preprocessing: ['NSABBS0001', 'NSABBS0002', 'NSABBS0003', 'NSABBS0004', 'NSABBS0005', 'NSABBS0006', 'NSABHC0001', 'NSABHC0002', 'NSABHC0003', 'NSABHC0004', 'NSABHC0005', 'NSABHC0006', 'NSABHC0007', 'NSABHC0008', 'NSABHC0009', 'NSABHC0010', 'NSABHC0011', 'NSABHC0012', 'NSABHC0013', 'NSABHC0014', 'NSABHC0015', 'NSABHC0016', 'NSABHC0017', 'NSABHC0018', 'NSABHC0019', 'NSABHC0020', 'NSABHC0021', 'NSABHC0022', 'NSABHC0023', 'NSABHC0024', 'NSABHC0025', 'NSABHC0026', 'NSABHC0028', 'NSABHC0029', 'NSACHC0001', 'NSACHC0002', 'NSACHC0003', 'NSACHC0004', 'NSACOP0001', 'NSACOP0002', 'NSAMDD0001', 'NSAMDD0002', 'NSAMDD0003', 'NSAMDD0004', 'NSAMDD0005', 'NSAMDD0006', 'NSAMDD0007', 'NSAMDD0008', 'NSAMDD0009', 'NSAMDD0010', 'NSAMDD0011', 'NSAMDD0012', 'NSAMDD0013', 'NSAMDD0014', 'NSAMDD0015', 'NSAMDD0016', 'NSAMDD0017', 'NSAMDD0018', 'NSAMDD0019', 'NSAMDD0020', 'NSAMDD0021', 'NSAMDD0022', 'NSAMDD0023', 'NSAMDD0024', 'NSAMDD0025', 'NSAMDD0026', 'NSAMDD0027', 'NSAMDD0028', 'NSAMDD0029', 'NSAMDD0030', 'NSAMDD0031', 'NSAMDD0032', 'NSAMUL0001', 'NSAMUL0002', 'NSAMUL0003', 'NSAMUL0004', 'NSANAN0001', 'NSANAN0002', 'NSANET0001', 'NSANSS0001', 'NSANSS0002', 'NSTNSS0001', 'NSTSYB0001', 'NSTSYB0002', 'NSTSYB0003', 'NSTSYB0004', 'NSTSYB0005', 'NSTSYB0006', 'NSTSYB0007', 'NSTSYB0008', 'NSTSYB0009', 'NTAARP0001', 'NTAARP0002', 'NTAARP0003', 'NTAARP0004', 'NTAARP0005', 'NTABRT0001', 'NTABRT0002', 'NTABRT0003', 'NTABRT0004', 'NTABRT0005', 'NTABRT0006', 'NTABRT0007', 'NTABRT0008', 'NTADAC0001', 'NTADAC0002', 'NTADMR0001', 'NTADMR0002', 'NTAFIN0001', 'NTAFIN0002', 'NTAFIN0003', 'NTAFIN0004', 'NTAFIN0005', 'NTAFIN0006', 'NTAFIN0007', 'NTAFIN0008', 'NTAFIN0009', 'NTAFIN0010', 'NTAFIN0011', 'NTAFIN0012', 'NTAFIN0013', 'NTAFIN0014', 'NTAFIN0015', 'NTAFIN0016', 'NTAFIN0017', 'NTAFIN0018', 'NTAFIN0019', 'NTAFIN0020', 'NTAFIN0021', 'NTAFIN0022', 'NTAFIN0023', 'NTAFIN0024', 'NTAFIN0025', 'NTAFIN0026', 'NTAFIN0027', 'NTAFIN0028', 'NTAFIN0029', 'NTAFIN0030', 'NTAFIN0031', 'NTAFIN0032', 'NTAFIN0033', 'NTAGFU0001', 'NTAGFU0002', 'NTAGFU0003', 'NTAGFU0004', 'NTAGFU0005', 'NTAGFU0006', 'NTAGFU0007', 'NTAGFU0008', 'NTAGFU0009', 'NTAGFU0010', 'NTAGFU0011', 'NTAGFU0012', 'NTAGFU0013', 'NTAGFU0014', 'NTAGFU0015', 'NTAGFU0016', 'NTAGFU0017', 'NTAGFU0018', 'NTAGFU0019', 'NTAGFU0020', 'NTAGFU0021', 'NTAGFU0022', 'NTAGFU0023', 'NTAGFU0024', 'NTAGFU0025', 'NTAGFU0026', 'NTAGFU0027', 'NTAGFU0028', 'NTAGFU0029', 'NTAGFU0030', 'NTAGFU0031', 'NTAGFU0032', 'NTAGFU0033', 'NTAGFU0034', 'NTAGFU0035', 'NTAGFU0036', 'NTAGFU0037', 'NTAGFU0038', 'NTAGFU0039', 'NTAGFU0040', 'NTAGFU0041', 'NTAMAC0001', 'NTAMAC0002', 'NTAMAC0003', 'NTAMGD0001', 'NTAMGD0002', 'NTAMGD0003', 'NTAMGD0004', 'NTAMGD0005', 'NTAPCK0001', 'NTAPCK0002', 'NTAPCK0003', 'NTAPCK0004', 'NTAPCK0005', 'NTAPCK0006', 'NTAPCK0007', 'NTAPCK1009', 'NTAPCK1010', 'NTAPCK1011', 'NTAPCK1012', 'NTAPCK2013', 'NTAPCK2014', 'NTASSD0001', 'NTASSD0003', 'NTASSD0004', 'NTASSD0005', 'NTASSD0006', 'NTASSD0007', 'NTASSD0008', 'NTASSD0009', 'NTASSD0010', 'NTASSD0011', 'NTASSD0012', 'NTASSD0013', 'NTASSD0014', 'NTASSD0015', 'NTASSD0016', 'NTASSD0017', 'NTASSD0018', 'NTASSD0019', 'NTASTU0001', 'NTASTU0002', 'NTASTU0003', 'NTASTU0004', 'NTASTU0005', 'NTATAN0001', 'NTATAN0002', 'NTATAN0003', 'NTATAN0004', 'NTTDAB0001', 'NTTDAC0001', 'NTTDMR0001', 'NTTDMR0002', 'NTTDMR0003', 'NTTMGD0001', 'NTTPCK0001', 'NTTSTU0001', 'QDABBN0001', 'QDABBN0002', 'QDABBS0001', 'QDABBS0002', 'QDABBS0003', 'QDABBS0004', 'QDABBS0005', 'QDABBS0006', 'QDABBS0007', 'QDABBS0008', 'QDABBS0009', 'QDABBS0010', 'QDACHC0001', 'QDACHC0002', 'QDACHC0003', 'QDACHC0004', 'QDACHC0005', 'QDACHC0006', 'QDACHC0007', 'QDACYP0001', 'QDACYP0002', 'QDACYP0003', 'QDACYP0004', 'QDACYP0005', 'QDACYP0006', 'QDACYP0007', 'QDACYP0008', 'QDACYP0009', 'QDACYP0010', 'QDACYP0011', 'QDACYP0012', 'QDACYP0013', 'QDACYP0014', 'QDACYP0015', 'QDACYP0016', 'QDACYP0017', 'QDACYP0018', 'QDACYP0019', 'QDACYP0020', 'QDACYP0021', 'QDACYP0022', 'QDACYP0023', 'QDACYP0024', 'QDADEU0001', 'QDAEIU0001', 'QDAEIU0002', 'QDAEIU0003', 'QDAEIU0004', 'QDAEIU0005', 'QDAEIU0006', 'QDAEIU0007', 'QDAEIU0008', 'QDAEIU0009', 'QDAEIU0010', 'QDAGUP0001', 'QDAGUP0002', 'QDAGUP0003', 'QDAGUP0004', 'QDAGUP0005', 'QDAGUP0006', 'QDAGUP0007', 'QDAGUP0008', 'QDAGUP0009', 'QDAGUP0010', 'QDAGUP0011', 'QDAGUP0012', 'QDAGUP0013', 'QDAGUP0014', 'QDAGUP0015', 'QDAGUP0016', 'QDAGUP0017', 'QDAGUP0018', 'QDAGUP0019', 'QDAGUP0021', 'QDAGUP0022', 'QDAGUP0023', 'QDAGUP0024', 'QDAGUP0026', 'QDAGUP0027', 'QDAGUP0028', 'QDAGUP0029', 'QDAGUP0030', 'QDAGUP0031', 'QDAMGD0001', 'QDAMGD0002', 'QDAMGD0003', 'QDAMGD0004', 'QDAMGD0005', 'QDAMGD0006', 'QDAMGD0007', 'QDAMGD0008', 'QDAMGD0009', 'QDAMGD0010', 'QDAMGD0011', 'QDAMGD0012', 'QDAMGD0013', 'QDAMGD0014', 'QDAMGD0015', 'QDAMGD0016', 'QDAMGD0017', 'QDAMGD0018', 'QDAMGD0019', 'QDAMGD0020', 'QDAMGD0021', 'QDAMGD0022', 'QDAMGD0023', 'QDAMGD0024', 'QDAMGD0025', 'QDAMGD0026', 'QDAMGD0027', 'QDAMGD0028', 'QDAMII0001', 'QDAMII0002', 'QDAMUL0001', 'QDAMUL0002', 'QDAMUL0003', 'QDASEQ0001', 'QDASEQ0002', 'QDASEQ0003', 'QDASEQ0004', 'QDASSD0001', 'QDASSD0002', 'QDASSD0003', 'QDASSD0004', 'QDASSD0005', 'QDASSD0006', 'QDASSD0007', 'QDASSD0008', 'QDASSD0009', 'QDASSD0010', 'QDASSD0011', 'QDASSD0012', 'QDASSD0013', 'QDASSD0014', 'QDASSD0015', 'SAABHC0001', 'SAABHC0002', 'SAABHC0003', 'SAABHC0004', 'SAABHC0005', 'SAABHC0006', 'SAAEYB0002', 'SAAEYB0003', 'SAAEYB0004', 'SAAEYB0005', 'SAAEYB0006', 'SAAEYB0007', 'SAAEYB0008', 'SAAEYB0009', 'SAAEYB0010', 'SAAEYB0011', 'SAAEYB0012', 'SAAEYB0013', 'SAAEYB0021', 'SAAEYB0022', 'SAAEYB0023', 'SAAEYB0024', 'SAAEYB0025', 'SAAEYB0026', 'SAAEYB0027', 'SAAEYB0028', 'SAAEYB0029', 'SAAEYB0030', 'SAAEYB0031', 'SAAEYB0032', 'SAAEYB0033', 'SAAFLB0003', 'SAAFLB0004', 'SAAFLB0005', 'SAAFLB0006', 'SAAFLB0007', 'SAAFLB0008', 'SAAFLB0030', 'SAAFLB0031', 'SAAGAW0001', 'SAAGAW0002', 'SAAGAW0003', 'SAAGAW0004', 'SAAGAW0005', 'SAAGAW0006', 'SAAGAW0007', 'SAAGAW0008', 'SAAGVD0001', 'SAAGVD0002', 'SAAGVD0003', 'SAAGVD0004', 'SAAKAN0001', 'SAAKAN0002', 'SAAKAN0003', 'SAAKAN0004', 'SAAKAN0005', 'SAAKAN0006', 'SAAKAN0007', 'SAAKAN0008', 'SAAKAN0009', 'SAAKAN0010', 'SAAKAN0012', 'SAAMDD0007', 'SAAMDD0008', 'SAAMDD0009', 'SAAMDD0010', 'SAAMDD0011', 'SAANUL0001', 'SAANUL0002', 'SAANUL0003', 'SAANUL0004', 'SAARIV0001', 'SAARIV0002', 'SAARIV0003', 'SAARIV0004', 'SAARIV0005', 'SAARIV0006', 'SAARIV0007', 'SAARIV0008', 'SAARIV0009', 'SAASTP0001', 'SAASTP0002', 'SAASTP0003', 'SAASTP0004', 'SAASTP0005', 'SAASTP0006', 'SAASTP0007', 'SAASTP0008', 'SAASTP0009', 'SAASTP0010', 'SAASTP0011', 'SAASTP0012', 'SAASTP0013', 'SAASTP0014', 'SAASTP0015', 'SAASTP0016', 'SAASTP0017', 'SAASTP0018', 'SAASTP0019', 'SAASTP0020', 'SAASTP0021', 'SAASTP0022', 'SAASTP0023', 'SAASTP0024', 'SAASTP0025', 'SAASTP0026', 'SAASTP0027', 'SAASTP0028', 'SAASTP0029', 'SAASTP0030', 'SAASTP0031', 'SAASTP0032', 'SAASTP0033', 'SAASTP0034', 'SASMDD0001', 'SASMDD0002', 'SASMDD0003', 'SASMDD0004', 'SASMDD0005', 'SASMDD0006', 'SASMDD0008', 'SASMDD0009', 'SASMDD0011', 'SASMDD0012', 'SASMDD0013', 'SASMDD0014', 'SASMDD0016', 'SASMDD0017', 'SASMDD0018', 'SASRIV0001', 'SASRIV0002', 'SATEYB0001', 'SATEYB0002', 'SATFLB0001', 'SATFLB0002', 'SATFLB0003', 'SATFLB0004', 'SATFLB0005', 'SATFLB0006', 'SATFLB0008', 'SATFLB0009', 'SATFLB0010', 'SATFLB0011', 'SATFLB0013', 'SATFLB0015', 'SATFLB0016', 'SATFLB0017', 'SATFLB0018', 'SATFLB0019', 'SATFLB0020', 'SATFLB0021', 'SATFLB0022', 'SATFLB0023', 'SATFLB0024', 'SATFLB0025', 'SATFLB0026', 'SATFLB0027', 'SATFLB0028', 'SATKAN0001', 'SATKAN0002', 'SATKAN0003', 'SATKAN0004', 'SATSTP0001', 'SATSTP0002', 'SATSTP0003', 'SATSTP0004', 'SATSTP0005', 'SATSTP0006', 'SATSTP0007', 'SATSTP0008', 'TCABEL0001', 'TCABEL0002', 'TCABEL0003', 'TCATCH0001', 'TCATCH0002', 'TCATCH0003', 'TCATCH0004', 'TCATCH0005', 'TCATCH0006', 'TCATCH0007', 'TCATCH0008', 'TCATCH0009', 'TCATCH0010', 'TCATCH0011', 'TCATCH0012', 'TCATNM0001', 'TCATNM0002', 'TCATNM0003', 'TCATNM0004', 'TCATNM0005', 'TCATNM0006', 'VCAAUA0001', 'VCAAUA0002', 'VCAAUA0003', 'VCAAUA0004', 'VCAAUA0005', 'VCAAUA0006', 'VCAAUA0007', 'VCAAUA0008', 'VCAAUA0009', 'VCAAUA0010', 'VCAAUA0011', 'VCAAUA0012', 'VCAAUA0013', 'VCAAUA0014', 'VCAAUA0015', 'VCAMDD0001', 'VCAMDD0002', 'VCAMDD0003', 'WAAAVW0001', 'WAAAVW0002', 'WAAAVW0003', 'WAAAVW0004', 'WAAAVW0005', 'WAAAVW0006', 'WAAAVW0007', 'WAACAR0001', 'WAACAR0002', 'WAACAR0003', 'WAACAR0004', 'WAACEK0001', 'WAACEK0002', 'WAACEK0003', 'WAACOO0001', 'WAACOO0003', 'WAACOO0004', 'WAACOO0005', 'WAACOO0006', 'WAACOO0007', 'WAACOO0008', 'WAACOO0009', 'WAACOO0010', 'WAACOO0011', 'WAACOO0012', 'WAACOO0016', 'WAACOO0017', 'WAACOO0018', 'WAACOO0019', 'WAACOO0020', 'WAACOO0021', 'WAACOO0022', 'WAACOO0023', 'WAACOO0024', 'WAACOO0025', 'WAACOO0026', 'WAACOO0027', 'WAACOO0028', 'WAACOO0029', 'WAACOO0030', 'WAACOO0031', 'WAACOO0032', 'WAADAL0001', 'WAADAL0002', 'WAADAL0003', 'WAADAL0004', 'WAADAL0005', 'WAAESP0001', 'WAAGAS0001', 'WAAGAS0002', 'WAAGES0001', 'WAAGES0002', 'WAAGES0003', 'WAAGES0004', 'WAAGES0005', 'WAAGSD0001', 'WAAGVD0001', 'WAAHAM0001', 'WAAHAM0002', 'WAAHAM0003', 'WAAHAM0004', 'WAAHAM0005', 'WAAHAM0006', 'WAAJAF0001', 'WAAJAF0002', 'WAAJAF0003', 'WAALSD0001', 'WAALSD0002', 'WAALSD0003', 'WAAMAL0001', 'WAAMAL0002', 'WAAMAL0003', 'WAAMUR0001', 'WAAMUR0002', 'WAAMUR0003', 'WAAMUR0004', 'WAAMUR0005', 'WAAMUR0006', 'WAAMUR0007', 'WAAMUR0008', 'WAAMUR0028', 'WAAMUR0029', 'WAAMUR0030', 'WAAMUR0031', 'WAANOK0001', 'WAANOK0002', 'WAANOK0003', 'WAANOK0004', 'WAANOK0005', 'WAANOK0006', 'WAANOK0007', 'WAANOK0008', 'WAANUL0001', 'WAANUL0002', 'WAANUL0003', 'WAANUL0004', 'WAANUL0005', 'WAANUL0006', 'WAANUL0007', 'WAANUL0008', 'WAANUL0009', 'WAAPIL0001', 'WAAPIL0002', 'WAAPIL0003', 'WAAPIL0004', 'WAAPIL0005', 'WAAPIL0006', 'WAAPIL0007', 'WAAPIL0008', 'WAAPIL0009', 'WAAPIL0010', 'WAAPIL0011', 'WAAPIL0012', 'WAAPIL0013', 'WAAPIL0014', 'WAAPIL0015', 'WAAPIL0016', 'WAAPIL0017', 'WAAPIL0018', 'WAAPIL0019', 'WAAPIL0020', 'WAAPIL0021', 'WAAPIL0022', 'WAAPIL0023', 'WAAPIL0024', 'WAAPIL0025', 'WAAPIL0026', 'WAAPIL0027', 'WAAPIL0028', 'WAAPIL0029', 'WAAPIL0030', 'WAAPIL0031', 'WAAPIL0032', 'WAAPIL0033', 'WAAPIL0034', 'WAAPIL0035', 'WAASWA0001', 'WAASWA0002', 'WAASWA0003', 'WAASWA0004', 'WAAVIB0001', 'WAAVIB0002', 'WAAVIB0003', 'WAAVIB0004', 'WAAYAL0002', 'WAAYAL0004', 'WAAYAL0005', 'WAAYAL0006', 'WAAYAL0007', 'WAAYAL0008', 'WAGCOO0001', 'WAGCOO0002', 'WAGCOO0004']
Processing Data for NSABBS0001, 1/735
Data for NSABBS0001 Exported  1/735
Processing Data for NSABBS0002, 2/735
Data for NSABBS0002 Exported  2/735
Processing Data for NSABBS0003, 3/735
Data for NSABBS0003 Exported  3/735
Processing Data for NSABBS0004, 4/735
Data for NSABBS0004 Exported  4/735
Processing Data for NSABBS0005, 5/735
Data for NSABBS0005 Exported  5/735
Processing Data for NSABBS0006, 6/735
Data for NSABBS0006 Exported  6/735
Processing Data for NSABHC0001, 7/735
Data for NSABHC0001 Exported  7/735
Processing Data for NSABHC0002, 8/735
Data for NSABHC0002 Exported  8/735
Processing Data for NSABHC0003, 9/735
Data for NSABHC0003 Exported  9/735

In [14]:
## Sanity Checks

In [15]:
## Check if the difference is mainly to do with leap years 

for site_location_name in all_dea_fc:
    
    new_file = pd.read_csv(f"C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/DATASETS/DEA_FC_PROCESSED/MODELLED_PREPROCESSED/Input_DataSet_{site_location_name}.csv")
    old_file = pd.read_csv(f"C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/DATASETS/DEA_FC_PROCESSED/MODELLED_PREPROCESSED_OLD/Input_DataSet_{site_location_name}.csv")
    difference_date_set = set(new_file.time).difference(set(old_file.time))
    
    if difference_date_set:
        for date in difference_date_set:
            date_obj = datetime.strptime(date, '%Y-%m-%d')
            print(f'Leap Year ({date_obj.year}) = {date_obj.year % 4 == 0}')
    
    # Results seem to suggest leap-year handling was the cause of the length of the time series difference
    # But, now I should check if the savitzky-golay filter values are identical (they should be), if YYYY-12-31
    #   dates were excluded post filtering

Leap Year (2008) = True
Leap Year (2008) = True
Leap Year (2008) = True
Leap Year (2008) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2000) = True
Leap Year (2008) = True
Leap Year (2008) = True
Leap Year (2008) = True
Leap Year (2008) = True
Leap Year (2012) = True
Leap Year (2012) = True
Leap Year (2012) = True
Leap Year (2012) = True
Leap Year (2012) = True
Leap Year (2012) = True
Leap Year (2012) = True
Leap Year (2012) = True

KeyboardInterrupt:

In [ ]:
all_dea_fc

['NSABBS0001',
 'NSABBS0002',
 'NSABBS0003',
 'NSABBS0004',
 'NSABBS0005',
 'NSABBS0006',
 'NSABHC0001',
 'NSABHC0002',
 'NSABHC0003',
 'NSABHC0004',
 'NSABHC0005',
 'NSABHC0006',
 'NSABHC0007',
 'NSABHC0008',
 'NSABHC0009',
 'NSABHC0010',
 'NSABHC0011',
 'NSABHC0012',
 'NSABHC0013',
 'NSABHC0014',
 'NSABHC0015',
 'NSABHC0016',
 'NSABHC0017',
 'NSABHC0018',
 'NSABHC0019',
 'NSABHC0020',
 'NSABHC0021',
 'NSABHC0022',
 'NSABHC0023',
 'NSABHC0024',
 'NSABHC0025',
 'NSABHC0026',
 'NSABHC0028',
 'NSABHC0029',
 'NSACHC0001',
 'NSACHC0002',
 'NSACHC0003',
 'NSACHC0004',
 'NSACOP0001',
 'NSACOP0002',
 'NSAMDD0001',
 'NSAMDD0002',
 'NSAMDD0003',
 'NSAMDD0004',
 'NSAMDD0005',
 'NSAMDD0006',
 'NSAMDD0007',
 'NSAMDD0008',
 'NSAMDD0009',
 'NSAMDD0010',
 'NSAMDD0011',
 'NSAMDD0012',
 'NSAMDD0013',
 'NSAMDD0014',
 'NSAMDD0015',
 'NSAMDD0016',
 'NSAMDD0017',
 'NSAMDD0018',
 'NSAMDD0019',
 'NSAMDD0020',
 'NSAMDD0021',
 'NSAMDD0022',
 'NSAMDD0023',
 'NSAMDD0024',
 'NSAMDD0025',
 'NSAMDD0026',
 'NSAMDD0027',
 'NSAMDD0028',
 'NSAMDD0029',
 'NSAMDD0030',
 'NSAMDD0031',
 'NSAMDD0032',
 'NSAMUL0001',
 'NSAMUL0002',
 'NSAMUL0003',
 'NSAMUL0004',
 'NSANAN0001',
 'NSANAN0002',
 'NSANET0001',
 'NSANSS0001',
 'NSANSS0002',
 'NSTNSS0001',
 'NSTSYB0001',
 'NSTSYB0002',
 'NSTSYB0003',
 'NSTSYB0004',
 'NSTSYB0005',
 'NSTSYB0006',
 'NSTSYB0007',
 'NSTSYB0008',
 'NSTSYB0009',
 'NTAARP0001',
 'NTAARP0002',
 'NTAARP0003',
 'NTAARP0004',
 'NTAARP0005',
 'NTABRT0001',
 'NTABRT0002',
 'NTABRT0003',
 'NTABRT0004',
 'NTABRT0005',
 'NTABRT0006',
 'NTABRT0007',
 'NTABRT0008',
 'NTADAC0001',
 'NTADAC0002',
 'NTADMR0001',
 'NTADMR0002',
 'NTAFIN0001',
 'NTAFIN0002',
 'NTAFIN0003',
 'NTAFIN0004',
 'NTAFIN0005',
 'NTAFIN0006',
 'NTAFIN0007',
 'NTAFIN0008',
 'NTAFIN0009',
 'NTAFIN0010',
 'NTAFIN0011',
 'NTAFIN0012',
 'NTAFIN0013',
 'NTAFIN0014',
 'NTAFIN0015',
 'NTAFIN0016',
 'NTAFIN0017',
 'NTAFIN0018',
 'NTAFIN0019',
 'NTAFIN0020',
 'NTAFIN0021',
 'NTAFIN0022',
 'NTAFIN0023',
 'NTAFIN0024',
 'NTAFIN0025',
 'NTAFIN0026',
 'NTAFIN0027',
 'NTAFIN0028',
 'NTAFIN0029',
 'NTAFIN0030',
 'NTAFIN0031',
 'NTAFIN0032',
 'NTAFIN0033',
 'NTAGFU0001',
 'NTAGFU0002',
 'NTAGFU0003',
 'NTAGFU0004',
 'NTAGFU0005',
 'NTAGFU0006',
 'NTAGFU0007',
 'NTAGFU0008',
 'NTAGFU0009',
 'NTAGFU0010',
 'NTAGFU0011',
 'NTAGFU0012',
 'NTAGFU0013',
 'NTAGFU0014',
 'NTAGFU0015',
 'NTAGFU0016',
 'NTAGFU0017',
 'NTAGFU0018',
 'NTAGFU0019',
 'NTAGFU0020',
 'NTAGFU0021',
 'NTAGFU0022',
 'NTAGFU0023',
 'NTAGFU0024',
 'NTAGFU0025',
 'NTAGFU0026',
 'NTAGFU0027',
 'NTAGFU0028',
 'NTAGFU0029',
 'NTAGFU0030',
 'NTAGFU0031',
 'NTAGFU0032',
 'NTAGFU0033',
 'NTAGFU0034',
 'NTAGFU0035',
 'NTAGFU0036',
 'NTAGFU0037',
 'NTAGFU0038',
 'NTAGFU0039',
 'NTAGFU0040',
 'NTAGFU0041',
 'NTAMAC0001',
 'NTAMAC0002',
 'NTAMAC0003',
 'NTAMGD0001',
 'NTAMGD0002',
 'NTAMGD0003',
 'NTAMGD0004',
 'NTAMGD0005',
 'NTAPCK0001',
 'NTAPCK0002',
 'NTAPCK0003',
 'NTAPCK0004',
 'NTAPCK0005',
 'NTAPCK0006',
 'NTAPCK0007',
 'NTAPCK1009',
 'NTAPCK1010',
 'NTAPCK1011',
 'NTAPCK1012',
 'NTAPCK2013',
 'NTAPCK2014',
 'NTASSD0001',
 'NTASSD0003',
 'NTASSD0004',
 'NTASSD0005',
 'NTASSD0006',
 'NTASSD0007',
 'NTASSD0008',
 'NTASSD0009',
 'NTASSD0010',
 'NTASSD0011',
 'NTASSD0012',
 'NTASSD0013',
 'NTASSD0014',
 'NTASSD0015',
 'NTASSD0016',
 'NTASSD0017',
 'NTASSD0018',
 'NTASSD0019',
 'NTASTU0001',
 'NTASTU0002',
 'NTASTU0003',
 'NTASTU0004',
 'NTASTU0005',
 'NTATAN0001',
 'NTATAN0002',
 'NTATAN0003',
 'NTATAN0004',
 'NTTDAB0001',
 'NTTDAC0001',
 'NTTDMR0001',
 'NTTDMR0002',
 'NTTDMR0003',
 'NTTMGD0001',
 'NTTPCK0001',
 'NTTSTU0001',
 'QDABBN0001',
 'QDABBN0002',
 'QDABBS0001',
 'QDABBS0002',
 'QDABBS0003',
 'QDABBS0004',
 'QDABBS0005',
 'QDABBS0006',
 'QDABBS0007',
 'QDABBS0008',
 'QDABBS0009',
 'QDABBS0010',
 'QDACHC0001',
 'QDACHC0002',
 'QDACHC0003',
 'QDACHC0004',
 'QDACHC0005',
 'QDACHC0006',
 'QDACHC0007',
 'QDACYP0001',
 'QDACYP0002',
 'QDACYP0003',
 'QDACYP0004',
 'QDACYP0005',
 'QDACYP0006',
 'QDACYP0007',
 'QDACYP0008',
 'QDACYP0009',
 'QDACYP0010',
 'QDACYP0011',
 'QDACYP0012',
 'QDACYP0013',
 'QDACYP0014',
 'QDACYP0015',
 'QDACYP0016',
 'QDACYP0017',
 'QDACYP0018',
 'QDACYP0019',
 'QDACYP0020',
 'QDACYP0021',
 'QDACYP0022',
 'QDACYP0023',
 'QDACYP0024',
 'QDADEU0001',
 'QDAEIU0001',
 'QDAEIU0002',
 'QDAEIU0003',
 'QDAEIU0004',
 'QDAEIU0005',
 'QDAEIU0006',
 'QDAEIU0007',
 'QDAEIU0008',
 'QDAEIU0009',
 'QDAEIU0010',
 'QDAGUP0001',
 'QDAGUP0002',
 'QDAGUP0003',
 'QDAGUP0004',
 'QDAGUP0005',
 'QDAGUP0006',
 'QDAGUP0007',
 'QDAGUP0008',
 'QDAGUP0009',
 'QDAGUP0010',
 'QDAGUP0011',
 'QDAGUP0012',
 'QDAGUP0013',
 'QDAGUP0014',
 'QDAGUP0015',
 'QDAGUP0016',
 'QDAGUP0017',
 'QDAGUP0018',
 'QDAGUP0019',
 'QDAGUP0021',
 'QDAGUP0022',
 'QDAGUP0023',
 'QDAGUP0024',
 'QDAGUP0026',
 'QDAGUP0027',
 'QDAGUP0028',
 'QDAGUP0029',
 'QDAGUP0030',
 'QDAGUP0031',
 'QDAMGD0001',
 'QDAMGD0002',
 'QDAMGD0003',
 'QDAMGD0004',
 'QDAMGD0005',
 'QDAMGD0006',
 'QDAMGD0007',
 'QDAMGD0008',
 'QDAMGD0009',
 'QDAMGD0010',
 'QDAMGD0011',
 'QDAMGD0012',
 'QDAMGD0013',
 'QDAMGD0014',
 'QDAMGD0015',
 'QDAMGD0016',
 'QDAMGD0017',
 'QDAMGD0018',
 'QDAMGD0019',
 'QDAMGD0020',
 'QDAMGD0021',
 'QDAMGD0022',
 'QDAMGD0023',
 'QDAMGD0024',
 'QDAMGD0025',
 'QDAMGD0026',
 'QDAMGD0027',
 'QDAMGD0028',
 'QDAMII0001',
 'QDAMII0002',
 'QDAMUL0001',
 'QDAMUL0002',
 'QDAMUL0003',
 'QDASEQ0001',
 'QDASEQ0002',
 'QDASEQ0003',
 'QDASEQ0004',
 'QDASSD0001',
 'QDASSD0002',
 'QDASSD0003',
 'QDASSD0004',
 'QDASSD0005',
 'QDASSD0006',
 'QDASSD0007',
 'QDASSD0008',
 'QDASSD0009',
 'QDASSD0010',
 'QDASSD0011',
 'QDASSD0012',
 'QDASSD0013',
 'QDASSD0014',
 'QDASSD0015',
 'SAABHC0001',
 'SAABHC0002',
 'SAABHC0003',
 'SAABHC0004',
 'SAABHC0005',
 'SAABHC0006',
 'SAAEYB0002',
 'SAAEYB0003',
 'SAAEYB0004',
 'SAAEYB0005',
 'SAAEYB0006',
 'SAAEYB0007',
 'SAAEYB0008',
 'SAAEYB0009',
 'SAAEYB0010',
 'SAAEYB0011',
 'SAAEYB0012',
 'SAAEYB0013',
 'SAAEYB0021',
 'SAAEYB0022',
 'SAAEYB0023',
 'SAAEYB0024',
 'SAAEYB0025',
 'SAAEYB0026',
 'SAAEYB0027',
 'SAAEYB0028',
 'SAAEYB0029',
 'SAAEYB0030',
 'SAAEYB0031',
 'SAAEYB0032',
 'SAAEYB0033',
 'SAAFLB0003',
 'SAAFLB0004',
 'SAAFLB0005',
 'SAAFLB0006',
 'SAAFLB0007',
 'SAAFLB0008',
 'SAAFLB0030',
 'SAAFLB0031',
 'SAAGAW0001',
 'SAAGAW0002',
 'SAAGAW0003',
 'SAAGAW0004',
 'SAAGAW0005',
 'SAAGAW0006',
 'SAAGAW0007',
 'SAAGAW0008',
 'SAAGVD0001',
 'SAAGVD0002',
 'SAAGVD0003',
 'SAAGVD0004',
 'SAAKAN0001',
 'SAAKAN0002',
 'SAAKAN0003',
 'SAAKAN0004',
 'SAAKAN0005',
 'SAAKAN0006',
 'SAAKAN0007',
 'SAAKAN0008',
 'SAAKAN0009',
 'SAAKAN0010',
 'SAAKAN0012',
 'SAAMDD0007',
 'SAAMDD0008',
 'SAAMDD0009',
 'SAAMDD0010',
 'SAAMDD0011',
 'SAANUL0001',
 'SAANUL0002',
 'SAANUL0003',
 'SAANUL0004',
 'SAARIV0001',
 'SAARIV0002',
 'SAARIV0003',
 'SAARIV0004',
 'SAARIV0005',
 'SAARIV0006',
 'SAARIV0007',
 'SAARIV0008',
 'SAARIV0009',
 'SAASTP0001',
 'SAASTP0002',
 'SAASTP0003',
 'SAASTP0004',
 'SAASTP0005',
 'SAASTP0006',
 'SAASTP0007',
 'SAASTP0008',
 'SAASTP0009',
 'SAASTP0010',
 'SAASTP0011',
 'SAASTP0012',
 'SAASTP0013',
 'SAASTP0014',
 'SAASTP0015',
 'SAASTP0016',
 'SAASTP0017',
 'SAASTP0018',
 'SAASTP0019',
 'SAASTP0020',
 'SAASTP0021',
 'SAASTP0022',
 'SAASTP0023',
 'SAASTP0024',
 'SAASTP0025',
 'SAASTP0026',
 'SAASTP0027',
 'SAASTP0028',
 'SAASTP0029',
 'SAASTP0030',
 'SAASTP0031',
 'SAASTP0032',
 'SAASTP0033',
 'SAASTP0034',
 'SASMDD0001',
 'SASMDD0002',
 'SASMDD0003',
 'SASMDD0004',
 'SASMDD0005',
 'SASMDD0006',
 'SASMDD0008',
 'SASMDD0009',
 'SASMDD0011',
 'SASMDD0012',
 'SASMDD0013',
 'SASMDD0014',
 'SASMDD0016',
 'SASMDD0017',
 'SASMDD0018',
 'SASRIV0001',
 'SASRIV0002',
 'SATEYB0001',
 'SATEYB0002',
 'SATFLB0001',
 'SATFLB0002',
 'SATFLB0003',
 'SATFLB0004',
 'SATFLB0005',
 'SATFLB0006',
 'SATFLB0008',
 'SATFLB0009',
 'SATFLB0010',
 'SATFLB0011',
 'SATFLB0013',
 'SATFLB0015',
 'SATFLB0016',
 'SATFLB0017',
 'SATFLB0018',
 'SATFLB0019',
 'SATFLB0020',
 'SATFLB0021',
 'SATFLB0022',
 'SATFLB0023',
 'SATFLB0024',
 'SATFLB0025',
 'SATFLB0026',
 'SATFLB0027',
 'SATFLB0028',
 'SATKAN0001',
 'SATKAN0002',
 'SATKAN0003',
 'SATKAN0004',
 'SATSTP0001',
 'SATSTP0002',
 'SATSTP0003',
 'SATSTP0004',
 'SATSTP0005',
 'SATSTP0006',
 'SATSTP0007',
 'SATSTP0008',
 'TCABEL0001',
 'TCABEL0002',
 'TCABEL0003',
 'TCATCH0001',
 'TCATCH0002',
 'TCATCH0003',
 'TCATCH0004',
 'TCATCH0005',
 'TCATCH0006',
 'TCATCH0007',
 'TCATCH0008',
 'TCATCH0009',
 'TCATCH0010',
 'TCATCH0011',
 'TCATCH0012',
 'TCATNM0001',
 'TCATNM0002',
 'TCATNM0003',
 'TCATNM0004',
 'TCATNM0005',
 'TCATNM0006',
 'VCAAUA0001',
 'VCAAUA0002',
 'VCAAUA0003',
 'VCAAUA0004',
 'VCAAUA0005',
 'VCAAUA0006',
 'VCAAUA0007',
 'VCAAUA0008',
 'VCAAUA0009',
 'VCAAUA0010',
 'VCAAUA0011',
 'VCAAUA0012',
 'VCAAUA0013',
 'VCAAUA0014',
 'VCAAUA0015',
 'VCAMDD0001',
 'VCAMDD0002',
 'VCAMDD0003',
 'WAAAVW0001',
 'WAAAVW0002',
 'WAAAVW0003',
 'WAAAVW0004',
 'WAAAVW0005',
 'WAAAVW0006',
 'WAAAVW0007',
 'WAACAR0001',
 'WAACAR0002',
 'WAACAR0003',
 'WAACAR0004',
 'WAACEK0001',
 'WAACEK0002',
 'WAACEK0003',
 'WAACOO0001',
 'WAACOO0003',
 'WAACOO0004',
 'WAACOO0005',
 'WAACOO0006',
 'WAACOO0007',
 'WAACOO0008',
 'WAACOO0009',
 'WAACOO0010',
 'WAACOO0011',
 'WAACOO0012',
 'WAACOO0016',
 'WAACOO0017',
 'WAACOO0018',
 'WAACOO0019',
 'WAACOO0020',
 'WAACOO0021',
 'WAACOO0022',
 'WAACOO0023',
 'WAACOO0024',
 'WAACOO0025',
 'WAACOO0026',
 'WAACOO0027',
 'WAACOO0028',
 'WAACOO0029',
 'WAACOO0030',
 'WAACOO0031',
 'WAACOO0032',
 'WAADAL0001',
 'WAADAL0002',
 'WAADAL0003',
 'WAADAL0004',
 'WAADAL0005',
 'WAAESP0001',
 'WAAGAS0001',
 'WAAGAS0002',
 'WAAGES0001',
 'WAAGES0002',
 'WAAGES0003',
 'WAAGES0004',
 'WAAGES0005',
 'WAAGSD0001',
 'WAAGVD0001',
 'WAAHAM0001',
 'WAAHAM0002',
 'WAAHAM0003',
 'WAAHAM0004',
 'WAAHAM0005',
 'WAAHAM0006',
 'WAAJAF0001',
 'WAAJAF0002',
 'WAAJAF0003',
 'WAALSD0001',
 'WAALSD0002',
 'WAALSD0003',
 'WAAMAL0001',
 'WAAMAL0002',
 'WAAMAL0003',
 'WAAMUR0001',
 'WAAMUR0002',
 'WAAMUR0003',
 'WAAMUR0004',
 'WAAMUR0005',
 'WAAMUR0006',
 'WAAMUR0007',
 'WAAMUR0008',
 'WAAMUR0028',
 'WAAMUR0029',
 'WAAMUR0030',
 'WAAMUR0031',
 'WAANOK0001',
 'WAANOK0002',
 'WAANOK0003',
 'WAANOK0004',
 'WAANOK0005',
 'WAANOK0006',
 'WAANOK0007',
 'WAANOK0008',
 'WAANUL0001',
 'WAANUL0002',
 'WAANUL0003',
 'WAANUL0004',
 'WAANUL0005',
 'WAANUL0006',
 'WAANUL0007',
 'WAANUL0008',
 'WAANUL0009',
 'WAAPIL0001',
 'WAAPIL0002',
 'WAAPIL0003',
 'WAAPIL0004',
 'WAAPIL0005',
 'WAAPIL0006',
 'WAAPIL0007',
 'WAAPIL0008',
 'WAAPIL0009',
 'WAAPIL0010',
 'WAAPIL0011',
 'WAAPIL0012',
 'WAAPIL0013',
 'WAAPIL0014',
 'WAAPIL0015',
 'WAAPIL0016',
 'WAAPIL0017',
 'WAAPIL0018',
 'WAAPIL0019',
 'WAAPIL0020',
 'WAAPIL0021',
 'WAAPIL0022',
 'WAAPIL0023',
 'WAAPIL0024',
 'WAAPIL0025',
 'WAAPIL0026',
 'WAAPIL0027',
 'WAAPIL0028',
 'WAAPIL0029',
 'WAAPIL0030',
 'WAAPIL0031',
 'WAAPIL0032',
 'WAAPIL0033',
 'WAAPIL0034',
 'WAAPIL0035',
 'WAASWA0001',
 'WAASWA0002',
 'WAASWA0003',
 'WAASWA0004',
 'WAAVIB0001',
 'WAAVIB0002',
 'WAAVIB0003',
 'WAAVIB0004',
 'WAAYAL0002',
 'WAAYAL0004',
 'WAAYAL0005',
 'WAAYAL0006',
 'WAAYAL0007',
 'WAAYAL0008',
 'WAGCOO0001',
 'WAGCOO0002',
 'WAGCOO0004']

In [34]:
## A test to see if we get identical result, even if we 

columns_of_interest = ['time', 'pv_filter']
passes = {}

for site_location_name in all_dea_fc:
    
    new_file = pd.read_csv(f"C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/DATASETS/DEA_FC_PROCESSED/MODELLED_PREPROCESSED/Input_DataSet_{site_location_name}.csv",
                           usecols= columns_of_interest)
    old_file = pd.read_csv(f"C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/DATASETS/DEA_FC_PROCESSED/MODELLED_PREPROCESSED_OLD/Input_DataSet_{site_location_name}.csv",
                           usecols= columns_of_interest)

    old_file = old_file.merge(new_file, left_on= 'time', right_on = 'time')
    passes[site_location_name] = bool(np.all(old_file['pv_filter_x'] == old_file['pv_filter_y']))

In [37]:
failled = list(filter(lambda item: item[1] == False, passes.items()))

In [76]:
len(failled)
failled

[('NSABHC0004', False),
 ('NSABHC0005', False),
 ('NSABHC0006', False),
 ('NSABHC0009', False),
 ('NSABHC0010', False),
 ('NSABHC0011', False),
 ('NSABHC0012', False),
 ('NSABHC0018', False),
 ('NSABHC0021', False),
 ('NSABHC0022', False),
 ('NSABHC0023', False),
 ('NSABHC0024', False),
 ('NSABHC0026', False),
 ('NSABHC0028', False),
 ('NSABHC0029', False),
 ('NSAMDD0005', False),
 ('NSAMDD0006', False),
 ('NSAMDD0023', False),
 ('NSAMDD0024', False),
 ('NSANSS0001', False),
 ('NSANSS0002', False),
 ('NTABRT0004', False),
 ('NTABRT0005', False),
 ('NTABRT0006', False),
 ('NTABRT0007', False),
 ('NTADMR0002', False),
 ('NTAFIN0002', False),
 ('NTAFIN0004', False),
 ('NTAFIN0005', False),
 ('NTAFIN0006', False),
 ('NTAFIN0007', False),
 ('NTAFIN0008', False),
 ('NTAFIN0009', False),
 ('NTAFIN0010', False),
 ('NTAFIN0011', False),
 ('NTAFIN0012', False),
 ('NTAFIN0013', False),
 ('NTAFIN0014', False),
 ('NTAFIN0015', False),
 ('NTAFIN0016', False),
 ('NTAGFU0036', False),
 ('NTAGFU0037', False),
 ('NTAGFU0038', False),
 ('NTAGFU0039', False),
 ('NTAGFU0040', False),
 ('NTAMAC0001', False),
 ('NTAMAC0002', False),
 ('NTAMAC0003', False),
 ('NTAMGD0001', False),
 ('NTAMGD0002', False),
 ('NTAPCK0005', False),
 ('NTASSD0001', False),
 ('NTASSD0003', False),
 ('NTASSD0004', False),
 ('NTASSD0005', False),
 ('NTASSD0006', False),
 ('NTASSD0007', False),
 ('NTASSD0008', False),
 ('NTASSD0009', False),
 ('NTASSD0010', False),
 ('NTATAN0001', False),
 ('NTATAN0002', False),
 ('NTATAN0003', False),
 ('NTATAN0004', False),
 ('QDABBN0001', False),
 ('QDABBN0002', False),
 ('QDACHC0004', False),
 ('QDACHC0005', False),
 ('QDACHC0006', False),
 ('QDACHC0007', False),
 ('QDACYP0006', False),
 ('QDACYP0009', False),
 ('QDACYP0018', False),
 ('QDACYP0019', False),
 ('QDACYP0020', False),
 ('QDACYP0021', False),
 ('QDACYP0022', False),
 ('QDACYP0023', False),
 ('QDACYP0024', False),
 ('QDAEIU0001', False),
 ('QDAEIU0002', False),
 ('QDAEIU0003', False),
 ('QDAEIU0004', False),
 ('QDAEIU0005', False),
 ('QDAEIU0006', False),
 ('QDAEIU0007', False),
 ('QDAGUP0007', False),
 ('QDAGUP0008', False),
 ('QDAGUP0009', False),
 ('QDAGUP0010', False),
 ('QDAGUP0011', False),
 ('QDAGUP0014', False),
 ('QDAGUP0015', False),
 ('QDAGUP0016', False),
 ('QDAGUP0017', False),
 ('QDAGUP0019', False),
 ('QDAGUP0021', False),
 ('QDAGUP0022', False),
 ('QDAGUP0023', False),
 ('QDAGUP0028', False),
 ('QDAMGD0001', False),
 ('QDAMGD0002', False),
 ('QDAMGD0003', False),
 ('QDAMGD0004', False),
 ('QDAMGD0005', False),
 ('QDAMGD0006', False),
 ('QDAMGD0007', False),
 ('QDAMGD0008', False),
 ('QDAMGD0013', False),
 ('QDAMGD0014', False),
 ('QDAMGD0015', False),
 ('QDAMGD0021', False),
 ('QDAMGD0022', False),
 ('QDAMGD0023', False),
 ('QDAMGD0024', False),
 ('QDAMGD0027', False),
 ('QDAMGD0028', False),
 ('QDAMII0002', False),
 ('QDASSD0006', False),
 ('QDASSD0007', False),
 ('QDASSD0010', False),
 ('QDASSD0011', False),
 ('QDASSD0012', False),
 ('QDASSD0013', False),
 ('QDASSD0014', False),
 ('QDASSD0015', False),
 ('SAABHC0001', False),
 ('SAABHC0002', False),
 ('SAABHC0003', False),
 ('SAABHC0004', False),
 ('SAABHC0005', False),
 ('SAABHC0006', False),
 ('SAAEYB0007', False),
 ('SAAEYB0009', False),
 ('SAAEYB0010', False),
 ('SAAEYB0025', False),
 ('SAAEYB0026', False),
 ('SAAEYB0027', False),
 ('SAAEYB0028', False),
 ('SAAEYB0029', False),
 ('SAAEYB0031', False),
 ('SAAEYB0033', False),
 ('SAAFLB0030', False),
 ('SAAFLB0031', False),
 ('SAAGAW0001', False),
 ('SAAGAW0002', False),
 ('SAAGAW0003', False),
 ('SAAGAW0004', False),
 ('SAAGAW0005', False),
 ('SAAGAW0006', False),
 ('SAAGAW0007', False),
 ('SAAGAW0008', False),
 ('SAAGVD0001', False),
 ('SAAGVD0002', False),
 ('SAAGVD0003', False),
 ('SAAKAN0007', False),
 ('SAAKAN0010', False),
 ('SAAKAN0012', False),
 ('SAANUL0002', False),
 ('SAANUL0003', False),
 ('SAANUL0004', False),
 ('SAARIV0007', False),
 ('SAARIV0008', False),
 ('SAARIV0009', False),
 ('SAASTP0006', False),
 ('SAASTP0007', False),
 ('SAASTP0008', False),
 ('SAASTP0009', False),
 ('SAASTP0029', False),
 ('SAASTP0030', False),
 ('SAASTP0031', False),
 ('SAASTP0032', False),
 ('SAASTP0033', False),
 ('SAASTP0034', False),
 ('SASMDD0005', False),
 ('SASMDD0006', False),
 ('SASMDD0017', False),
 ('SATFLB0013', False),
 ('SATFLB0016', False),
 ('SATFLB0017', False),
 ('SATFLB0018', False),
 ('SATFLB0019', False),
 ('SATFLB0020', False),
 ('SATFLB0021', False),
 ('SATFLB0022', False),
 ('SATFLB0023', False),
 ('SATFLB0028', False),
 ('SATKAN0001', False),
 ('SATSTP0001', False),
 ('SATSTP0002', False),
 ('SATSTP0003', False),
 ('SATSTP0004', False),
 ('SATSTP0006', False),
 ('SATSTP0007', False),
 ('SATSTP0008', False),
 ('TCATCH0001', False),
 ('TCATCH0002', False),
 ('TCATCH0003', False),
 ('TCATCH0004', False),
 ('TCATCH0005', False),
 ('TCATCH0006', False),
 ('TCATCH0007', False),
 ('TCATCH0008', False),
 ('TCATCH0009', False),
 ('TCATCH0010', False),
 ('TCATCH0011', False),
 ('TCATCH0012', False),
 ('TCATNM0001', False),
 ('TCATNM0002', False),
 ('TCATNM0004', False),
 ('TCATNM0006', False),
 ('VCAAUA0006', False),
 ('VCAAUA0011', False),
 ('VCAAUA0012', False),
 ('VCAAUA0013', False),
 ('VCAAUA0014', False),
 ('VCAAUA0015', False)]

In [64]:

site_location_name = failled[0][0]
new_file = pd.read_csv(f"C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/DATASETS/DEA_FC_PROCESSED/MODELLED_PREPROCESSED/Input_DataSet_{site_location_name}.csv",
                           usecols= columns_of_interest)
old_file = pd.read_csv(f"C:/Users/Krish Singh (Work)/Desktop/MRes_Publication_Repository_KKS/in-situ_vs_rs_paper/DATASETS/DEA_FC_PROCESSED/MODELLED_PREPROCESSED_OLD/Input_DataSet_{site_location_name}.csv",
                           usecols= columns_of_interest)

old_file_1 = old_file.merge(new_file, how = 'left', left_on= 'time', right_on = 'time')

In [65]:
mismatches = np.where((old_file_1['pv_filter_x'] == old_file_1['pv_filter_y']) == False)

In [75]:
old_file_1.iloc[mismatches]

      pv_filter_x        time  pv_filter_y
357     12.853465  1999-07-04    18.586686
358     18.586686  1999-07-04    12.853465
364     22.446241  1999-08-05    19.644519
365     19.644519  1999-08-05    22.446241
368     17.121520  1999-08-21    14.764332
...           ...         ...          ...
1583     9.941696  2021-11-29     7.762676
1588    13.953450  2021-12-15    15.422537
1589    15.422537  2021-12-15    13.953450
1594    11.136326  2021-12-31     9.880361
1595     9.880361  2021-12-31    11.136326

[66 rows x 3 columns]

In [66]:
old_file_1.iloc[mismatches].time

357     1999-07-04
358     1999-07-04
364     1999-08-05
365     1999-08-05
368     1999-08-21
           ...
1583    2021-11-29
1588    2021-12-15
1589    2021-12-15
1594    2021-12-31
1595    2021-12-31
Name: time, Length: 66, dtype: object

In [67]:
new_file.loc[new_file['time'].isin(old_file_1.iloc[mismatches].time)]

            time  pv_filter
356   1999-07-04  12.853465
357   1999-07-04  18.586686
361   1999-08-05  22.446241
362   1999-08-05  19.644519
363   1999-08-21  17.121520
...          ...        ...
1522  2021-11-29   9.941696
1525  2021-12-15  13.953450
1526  2021-12-15  15.422537
1529  2021-12-31  11.136326
1530  2021-12-31   9.880361

[66 rows x 2 columns]

In [68]:
old_file.loc[old_file['time'].isin(old_file_1.iloc[mismatches].time)]

      pv_filter        time
356   12.853465  1999-07-04
357   18.586686  1999-07-04
361   22.446241  1999-08-05
362   19.644519  1999-08-05
363   17.121520  1999-08-21
...         ...         ...
1522   9.941696  2021-11-29
1525  13.953450  2021-12-15
1526  15.422537  2021-12-15
1529  11.136326  2021-12-31
1530   9.880361  2021-12-31

[66 rows x 2 columns]

In [ ]:
new_file.loc[new_file['time'].isin(old_file.iloc[mismatches].time)]

In [ ]:
set(new_file.time).difference(set(old_file.time))

{'1996-12-31', '2016-12-31'}

In [ ]:
new_file.loc[new_file.time == '2008-12-31',:]

,time,Unnamed: 0,pv,npv,bs,ue,x,y,spatial_ref,pv_filter,npv_filter,bs_filter
414,2008-12-31,415,54.45,40.65,3.8,18.1,1595962.5,-3513013.5,3577,51.803459,41.903528,5.062438

In [ ]:
old_file.loc[old_file.time >= '2008-12-20',:]

,Unnamed: 0.1,Unnamed: 0,pv,npv,bs,ue,x,y,spatial_ref,pv_filter,...,tmax_lag,tmax_7,tmax_14,tmax_30,tmin_lag,tmin_7,tmin_14,tmin_30,time,CO2
413,413,414,48.95,42.80,6.850000,16.750000,1595962.5,-3513013.5,3577,50.632388,...,29.462891,163.738281,191.852539,439.746094,15.097656,71.477539,102.366211,217.370117,2008-12-23,384.42
414,414,416,50.25,42.60,5.850000,17.650000,1595962.5,-3513013.5,3577,51.809162,...,30.841797,192.441406,206.561523,446.560547,21.057617,97.708984,113.366211,225.077148,2009-01-08,386.05
415,415,417,52.45,41.95,4.300000,18.300000,1595962.5,-3513013.5,3577,52.693797,...,34.692383,185.743164,224.893555,466.278320,18.618164,93.327148,124.566406,242.717773,2009-01-16,386.05
416,416,418,49.90,44.75,4.250000,18.400000,1595962.5,-3513013.5,3577,52.412291,...,31.391602,176.833008,224.995117,492.128906,20.877930,103.238281,117.905273,267.048828,2009-01-24,386.05
417,417,419,55.00,41.00,2.833333,13.666667,1595970.0,-3513060.0,3577,50.689863,...,24.736328,151.826172,259.301758,530.417969,14.769531,92.179688,144.039062,298.081055,2009-02-17,386.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,793,795,63.20,27.10,7.800000,19.150000,1595962.5,-3513013.5,3577,62.710595,...,17.614258,119.828125,168.871094,313.971680,3.827148,55.314453,100.124023,166.050781,2022-11-04,416.49
794,794,796,63.95,28.55,5.550000,20.900000,1595962.5,-3513013.5,3577,63.146183,...,27.543945,125.494141,168.876953,349.761719,9.147461,63.372070,80.126953,174.179688,2022-11-20,416.49
795,795,797,63.60,29.15,5.300000,20.750000,1595962.5,-3513013.5,3577,63.027586,...,31.234375,143.683594,153.748047,350.361328,14.737305,51.970703,71.669922,161.534180,2022-11-28,416.49
796,796,798,61.15,31.00,6.050000,19.850000,1595962.5,-3513013.5,3577,62.361753,...,23.873047,155.556641,181.471680,379.963867,7.417969,67.617188,76.794922,163.702148,2022-12-14,416.49
797,797,799,60.05,33.30,4.600000,18.950000,1595962.5,-3513013.5,3577,61.222180,...,33.203125,177.838867,177.480469,402.876953,16.007812,93.278320,62.964844,167.316406,2022-12-30,416.49